config/routes.rb
Rails.application.routes.draw do

  get 'teachers/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :students,        only: [:index, :edit, :update, :show, :create, :new]
  resources :teachers,        only: [:edit, :update, :show, :create, :new]
  resources :reviews,         only: [:create, :destroy]
  resources :matches,           only: [:new, :create, :edit, :update, :destroy]
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
  has_many :matches
  has_many :students, through: :matches
  validates :user_id, presence: true
  validates :post_number, presence: true, length:{maximum:7}
  validates :appeal, presence: true, length:{maximum:140}

  geocoded_by :post_number
  after_validation :geocode

  #男性か女性かを判断する
  enum sex: {man: 10, woman: 20}


  def self.feed(user)
    
    @student = Student.find_by(user_id: user.id)
    if @student.japanese == 1
          japanese = Teacher.where(japanese: 1)
        else
          japanese = Array.new
    end
    if @student.math == 1
          math = Teacher.where(math: 1)
        else
          math = Array.new
    end
    if @student.social == 1
          social = Teacher.where(social: 1)
        else
          social = Array.new
    end
    if @student.science == 1
          science = Teacher.where(science: 1)
        else
          science = Array.new
    end
    if @student.english == 1
          english = Teacher.where(english: 1)
        else
          english = Array.new
    end

    teacher_subject = japanese | math | social | science | english

    @array = Array.new
    @array_distance = Array.new

    i = 0
    teacher_subject.each do |teacher|
      distance = User.distance(@student.latitude, @student.longitude, teacher.latitude, teacher.longitude)
      @array[i] = [teacher.user_id, distance.round(1)]

      @array_distance = [teacher.user_id, distance.round(1)]
      @array.insert(i,@array_distance)
      i += 1
    end

    @array_sort = @array.sort{ |a, b| a[1] <=> b[1] }
    @array_take = @array_sort[1..3]


    #その三人に対して一致している科目が何かを探す

    i = 0
    while i < 3
      subject = Array.new
      t = 0
      if Teacher.find_by(user_id: @array_take[i][0]).japanese == @student.japanese && @student.japanese == 1
        subject[t] = "japanese"
        t += 1
      end

      if Teacher.find_by(user_id: @array_take[i][0]).math == @student.math && @student.math == 1
        subject[t] = "math"
        t += 1
      end

      if Teacher.find_by(user_id: @array_take[i][0]).social == @student.social && @student.social == 1
        subject[t] = "social"
        t += 1
      end

      if Teacher.find_by(user_id: @array_take[i][0]).science == @student.science && @student.science == 1
        subject[t] = "science"
        t += 1
      end

      if Teacher.find_by(user_id: @array_take[i][0]).english == @student.english && @student.english == 1
        subject[t] = "english"
      end
      @array_take[i][2] = subject
      i += 1
    end
    return @array_take

  end


end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :create, :update]
  before_action :correct_user, only: [:edit, :update]

  def new
    @teacher = current_user.build_teacher
    @teacher.user_id = current_user.id

    @teacher.save
  end

  def index
  end

  def create
    @teacher = current_user.build_teacher(teacher_params)


    if @teacher.save
      # 保存の成功をここで扱う。
      flash[:info] = "Create My Page"
      redirect_to teacher_path(@teacher.user_id)
    else
      # redirect_to edit_student_path(id: @student.user.id)

    render 'edit'

    end
  end

  def edit
    if !Teacher.exists?(user_id: params[:id])

      @teacher = current_user.build_teacher
      @teacher.user_id = current_user.id

      @teacher.save
    else
      @teacher = Teacher.find_by(user_id: params[:id])
   end
  end

  def update
      @teacher = Teacher.find_by(user_id: params[:id])
     if @teacher.update_attributes(teacher_params)
       #更新に成功した場合
       flash[:success] = "MyPage updated"
      redirect_to url: teacher_path(@teacher.user_id)
     else
       render 'edit'
     end
   end

   def show
     #既に書かれているレビュー
     @teacher = Teacher.find_by(user_id:params[:id])  #レビューの対象となる先生を参照
     @user = User.find(@teacher.user_id)  #先生のidでuserを参照
     @reviews = @user.reviews #reviewsはuserテーブルと紐付いてる

     #新しいレビュー
     @new_review = @user.reviews.build
     @new_review.user_id = @user.id

     session[:teacher] = @user.id
     if @average = @user.reviews.get_review_average
     @average_100 = (@average / 5) * 100
    else
     @average = 0
     @average_100 = 0
   end

    @matches = Match.where(teacher_id: @teacher.user_id)
    
   end

  private

   def teacher_params
     params.require(:teacher).permit(:sex, :post_number, :japanese, :math, :science, :social, :english, :university_name, :fee, :appeal)
   end


end

app/helpers/teachers_helper.rb
module TeachersHelper
  def adjust_decimal(decimal)
    if (decimal == nil)
      0
    else
      decimal
    end
  end




end

app/views/teachers/_form.html.erb
<h3><%= f.label :sex %></h3>
<label class = "sex">男<%= f.radio_button :sex, :man %></label>
<label class = "sex">女<%= f.radio_button :sex, :woman %></label>

<h3>大学名<%= f.label :university_name %></h3>
<%= f.text_field :university_name, class: 'form-control' %>

<h3>郵便番号<%= f.label :post_number %></h3>
<%= f.text_field :post_number, class: 'form-control' %>

<h3>指導科目</h3>
<%= f.label :japanese, "Japanese" %>
<%= f.check_box :japanese, checked_value:1, unchecked_value:0 %>
<%= f.label :math, "Math" %>
<%= f.check_box :math, checked_value:1, unchecked_value:0 %>
<%= f.label :science, "Science" %>
<%= f.check_box :science, checked_value:1, unchecked_value:0 %>
<%= f.label :social, "Social" %>
<%= f.check_box :social, checked_value:1, unchecked_value:0 %>
<%= f.label :english, "English" %>
<%= f.check_box :english, checked_value:1, unchecked_value:0 %>

<h3>自己ＰＲ<%= f.label :appeal %></h3>
<%= f.text_area :appeal, class: 'field' %>

<p><%= f.submit yield(:button_text), class: "btn btn-primary" %></p>

app/views/teachers/edit.html.erb
<% provide(:title, "Edit teacher") %>
<% provide(:button_text, "Save changes") %>
<h1>Update your mypage</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@teacher, url: teacher_path(@teacher.user_id)) do |f| %>

    <%= render 'form', f: f %>

    <% end %>


  </div>
</div>

app/views/teachers/new.html.erb
<h1>Teachers#new</h1>
<p>Find me in app/views/teachers/new.html.erb</p>

<% provide(:title, "New teacher") %>
<% provide(:button_text, "Create My Page") %>
<h1>Create your mypage</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@teacher) do |f| %>

    <%= render 'form', f: f %>

    <% end %>


  </div>
</div>

app/views/teachers/show.html.erb
<h1>教師詳細ページ</h1>
<p>名前:<%= @user.name %></p>
<p>学歴:<%= @teacher.university_name %></p>
<p>希望授業料:<%= @teacher.fee %></p>
<p>性別:<%= @teacher.sex %></p>
<p>郵便番号:<%= @teacher.post_number %></p>
<p>担当科目:</p>
<p>自己ＰＲ:<%= @teacher.appeal %></p>



<!-- 評価を表示 -->
<div class="">
  <!-- style = "width: <% @average_100 %>%" -->
  <p><b>評価</b><%= @average.round(1) %>/5.0<div class = "star-rating-box"><span style="width:<%= @average_100 %>%" class="star-rating-css-top"></span></div></p>
</div>



<div class="">


<!-- ユーザーが生徒なら評価フォームを表示 -->
<% if current_user.status == "student" %>
  <%= form_for @new_review do |f| %>
    <span class="star-rating">
      <%= f.radio_button :review, value="1" %><i></i>
      <%= f.radio_button :review, value="2" %><i></i>
      <%= f.radio_button :review, value="3" %><i></i>
      <%= f.radio_button :review, value="4" %><i></i>
      <%= f.radio_button :review, value="5" %><i></i>
    </span>

    <div class="field">
      <%= f.text_area :content, placeholder: "コメント欄" %>
    </div>
    <%= f.submit "POST", class: "btn btn-large btn-primary" %>
  <% end %>

  <%= link_to "リクエストする", new_match_path %>


  <% end %>


  <h2>コメント</h2>
  <% @reviews.each do |review| %>
     <p><%= review.content %></p>
  <% end %>

</div>


<!-- ログインしているユーザーと一致すれば編集リンクを表示 -->
<% if @teacher.user_id == current_user.id %>
<%= link_to "Edit My Page", edit_teacher_path(current_user) %>



<h3>届いているリクエスト</h3>
<% @matches.each do |match| %>
  <p><%= link_to User.find(match.student_id).name, edit_match_path(match.id) %>
     <%= link_to "非承認",  match_path(match.id), method: :delete %>
  </p>

<% end %>






<% end %>