config/routes.rb
Rails.application.routes.draw do

  get 'teachers/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :students,        only: [:index, :edit, :update, :show, :create, :new]
  resources :teachers,        only: [:edit, :update, :show, :create, :new]
  resources :reviews,         only: [:create, :destroy]
  resources :matches,           only: [:new, :create, :edit, :update, :destroy]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top  navbar-inverse">
  <!-- ウィンドウ幅に合わせて可変 -->
  <div class="container-fluid">




    <%= link_to "LARN", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <!--スマホ用トグルボタンの設置-->
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>


        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", 'users_path' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <% if current_user.status == "student" %>
          <% if !Student.exists?(user_id: current_user.id) %>

              <li><%= link_to "My Page", new_student_path %></li>

          <% else %>
              <li><%= link_to "My Page", student_path(current_user) %></li>

          <% end %>

      <% elsif current_user.status == "teacher" %>
          <% if !Teacher.exists?(user_id: current_user.id) %>
              <li><%= link_to "My Page", new_teacher_path %></li>

          <% else %>
              <li><%= link_to "My Page", teacher_path(current_user) %></li>
          <% end %>
      <% end %>



              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LARN</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
  <div class="container">
    <%= yield %>
  </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>